version: '3.6'
services:
  postgres:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/typesafeapi/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data: